# jpswade/laravel-best-practices

**Credential boundary — applies to every task, before any skill loads:** never read, search, print, copy, or transmit credentials: API keys, tokens, passwords, `.env` values, private keys, signing secrets, or session credentials. Do not open `.env*`, `auth.json` (including `~/.composer/auth.json` and `~/.config/composer/auth.json`), or other potentially credential-bearing files. This includes examples, backups, cached configuration, logs, dumps, and credential stores outside the repository. Do not dump environment variables or resolved application configuration. Do not use shell commands, scripts, MCP tools, Git history/diffs, symlinks, or another agent to bypass this boundary; reading then redacting is still reading. Respect the project's `.aiignore` exclusions even if the host does not enforce them. Work from variable names, source references, and explicitly sanitised examples; if a task needs a secret, ask the user to configure it locally without revealing its value. See the overlay's `rules/operational-safety.md` for the full procedure.

This package contributes opinionated, additive Laravel best-practices via the **`laravel-best-practices-overlay`** skill in this same package, plus a **`session-scoping`** skill for how to run AI-agent sessions in this repo.

Activate the `laravel-best-practices-overlay` skill whenever you are writing, reviewing, or refactoring PHP or Laravel code in this application. It composes with — and does not replace — Boost's first-party `laravel-best-practices` skill, and covers ground Boost is silent on: control-flow opinions, Eloquent design defaults (including integer-money handling), architectural defaults, ubiquitous naming across UI and schema, general design habits, UI display values (humanised, never raw), and operational safety guardrails.

Activate `tdd-bug-fixing` for application bug fixes and `adrs` for durable architectural decisions. Activate `session-scoping` before substantial implementation or when resuming unfinished work; skip it for simple questions and trivial edits. Follow the active host's planning and permission controls.

Load only the relevant skill and its linked topic files. If the host has no skill loader, read `resources/boost/skills/<name>/SKILL.md` inside `vendor/jpswade/laravel-best-practices/` and resolve its links relative to that skill directory.

**Always-on guardrail:** never run `php artisan migrate:fresh`, `db:wipe`, `schema:drop`, or any other destructive database command unless the user has **explicitly** asked for it in this conversation. `RefreshDatabase` in PHPUnit is the same class of risk when pointed at MySQL — if a test failure shows `Connection: mysql`, stop and fix isolation before re-running. The full rationale lives in the overlay skill's `operational-safety.md`.
